
// login
export interface LoginData {
    user:       string;
    password:   string
}
export interface RegisterUser {
    name:       string,
    user:       string,
    sector:     string,
    password:   string,
    role:       string | null,
}

// Users
export interface LoginResponse {
    ok:    boolean;
    user:  User;
    token: string;
}
export interface User {
    name:      string;
    user:      string;
    role:      string;
    sector:    string;
    password:  string;
    show:      boolean;
    createdAt: string;
    updatedAt: string;
    uid:       string;
}

// ROLES
// Generated by https://quicktype.io

export interface RoleResponse {
    ok:    boolean;
    total?: number;
    roles: Role[];
}
export interface Role {
    name:      string;
    createdAt: string;
    updatedAt: string;
    id:        string;
}

// SECTOR
export interface SectorResponse {
    ok:      boolean;
    total:   number;
    sectors: Sector[];
}
export interface Sector {
    name:      string;
    createdAt: string;
    updatedAt: string;
    id:        string;
}

